development:
  adapter: postgresql
  encoding: unicode
  database: datalock_development

test:
  adapter: postgresql
  encoding: unicode
  database: datalock_test

staging:
  adapter: postgresql
  encoding: unicode
  database: datalock_staging

production:
  adapter: postgresql
  encoding: unicode
  database: datalock_production
